# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-25 06:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20161125_0543'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Author',
            new_name='AuthorMod',
        ),
    ]
